#!/bin/bash

### BEGIN INIT INFO
# Provides:          clusterd
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: cluster service
### END INIT INFO

set -e

. /lib/lsb/init-functions

NAME=iguana-hpc-usp
BIN=/usr/local/bin
DAEMON=$BIN/$NAME
PIDDIR=/run/$NAME
PIDFILE=$PIDDIR/$NAME.pid
EXIT=0

case $1 in
  start)

    # Exit if required binary is missing.
    if [ -f "$DAEMON" ]; then
        log_progress_msg "$DAEMON starting..."
    else
        log_failure_msg "FAILED to find $DAEMON"
        EXIT=3
    fi

    if [ -d "$PIDDIR" ]; then
        log_progress_msg "$PIDDIR ok..."
    else
        log_progress_msg "Creating $PIDDIR"
        mkdir "$PIDDIR"
    fi

    log_daemon_msg "Starting $NAME server" "$NAMEd" || true

    start-stop-daemon --start --background -m --quiet --oknodo \
        --pidfile $PIDFILE \
        --exec $DAEMON -- $OPTARGS --writepid $PIDFILE || STATUS=1

    log_end_msg 0

    dhclient

    exit $EXIT
    ;;
  stop)
    start-stop-daemon --stop --quiet --oknodo \
        --pidfile $PIDFILE --exec $DAEMON --retry 10
    exec kill -9 $PIDFILE
    exec killall $NAME
    ;;
  restart)
        $0 stop
        sleep 1
        $0 start
        ;;

  *)
        log_success_msg "Usage: $NAME {start|stop|status|restart}"
        exit 1
        ;;
esac

exit 0
